:jbake-version: 1.6.6
// TODO: Add test for the version above
= Gradle Plugin Development Toolbox

Painless Gradle plugins development.
The Gradle toolbox is a suite of high-quality Gradle plugins improving the developer experience of writing Gradle plugins.
It bridges the gaps in the development process offered by the Gradle team.
The https://nokee.dev/[Nokee team] developed the toolbox plugins and offer them for free to everyone.

*For more information, visit the link:https://nokee.dev/docs/nightly/manual/gradle-plugin-development.html[official project documentation]*

== Usage

Apply link:https://nokee.dev/docs/nightly/manual/plugin-references.html#sec:plugin-reference-gradledev[any of the toolbox plugins] to your build just like any other Gradle plugin:

.settings.gradle
[source,groovy]
----
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://repo.nokee.dev/release' }
    }
}
----

.build.gradle
[source,groovy,subs=attributes+]
----
plugins {
    id("dev.gradleplugins.java-gradle-plugin") version("{jbake-version}")
}
----

== Examples

Look at link:https://nokee.dev/docs/nightly/samples/#sec:samples-gradle-dev[all the samples demonstrating various use cases solved by Gradle toolbox plugins].

== Need Help?

* Get familiar with the link:https://nokee.dev/docs/nightly/manual/gradle-plugin-development.html[Toolbox Manual]
* Have a look at the link:https://nokee.dev/docs/nightly/samples/#sec:samples-gradle-dev[Samples]
* Join the link:https://gradle.com/slack-invite[Gradle Slack Channel]

== Contributing

If you're looking to contribute to Gradle toolbox or provide a patch/pull request, you can find more info link:https://github.com/gradle-plugins/toolbox/blob/master/CONTRIBUTING.md[here].

This project adheres to this link:https://github.com/gradle-plugins/toolbox/blob/master/CODE_OF_CONDUCT.adoc[Code of Conduct].
By participating, you are expected to uphold this code.
